AppGST/AppGST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',include('interfaces.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppGST/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from .forms import LoginForm

app_name='accounts'
urlpatterns = [ 
    path('signup/',views.signup, name='signup'),
    #path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True,authentication_form=LoginForm,), name='login'), 
    #path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='accounts:login'), name='logout'),
    path('logout/', views.logout_view, name='logout') 
]

AppGST/interfaces/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import HistogrammeAbsencesView, HistogrammeAbsencesViews



app_name='interfaces'
urlpatterns = [
    path('',views.accueil, name='accueil'),
    path('rechercher/', views.rechercher, name='rechercher'),
    path('rechercher_absence/', views.rechercher_absence, name='rechercher_absence'),

    
    path('ajouter_personnel/', views.ajouter_personnel, name='ajouter_personnel'),
    path('list_personnel/', views.list_personnel, name='list_personnel'),
    path('info_personnel/<int:matricule>/', views.info_personnel, name='info_personnel'),
    path('delete_personnel/<int:matricule>/', views.delete_personnel, name='delete_personnel'),
    path('edit_personnel/<int:matricule>/', views.edit_personnel, name='edit_personnel'),


    path('ajouter_absence/', views.ajouter_absence, name='ajouter_absence'),
    path('une_absence/<int:matricule>/', views.une_absence, name='une_absence'),
    path('historiques/', views.historiques, name='historiques'),
    path('absence/', views.absence, name='absence'),
    path('absences_personnel/<int:matricule>/', views.absences_personnel, name='absences_personnel'),
    path('edit_absence/<int:id>/', views.edit_absence, name='edit_absence'),
    path('delete_absence/<int:id>/', views.delete_absence, name='delete_absence'),
    path('disponibilite/', views.disponibilite, name='disponibilite'),


    path('histogramme-absences/', HistogrammeAbsencesView.as_view(), name='histogramme-absences'),
    path('histogramme-absences_anote/', HistogrammeAbsencesViews.as_view(), name='histogramme-absences_anote'),


]

AppGST/templates/bases/footer.html
<footer id="footer"  class="footer">
    <div class="container">
        <div class="footer-menu">
               <div class="row">
                   <div class="col-sm-3">
                        <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'interfaces:accueil'%}">GST<span>FRA</span></a>
                    </div><!--/.navbar-header-->
                </div>
           </div>
        </div>
        <div class="hm-footer-copyright">
            <div class="row">
                <div class="col-sm-5">
                    <p>
                        <div class='container text-center'>
                            Copyright &copy: {% now "Y" %} &middot <a href="{% url 'interfaces:accueil' %}">GST FRA</a>
                        </div>  
                    </p><!--/p-->
                </div>
            </div>
            
        </div><!--/.hm-footer-copyright-->
    </div><!--/.container-->

    <div id="scroll-Top">
        <div class="return-to-top">
            <i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
        </div>
        
    </div><!--/.scroll-Top-->
    
</footer>

AppGST/templates/bases/header.html
<section class="top-area">
    <div class="header-area">
        <!-- Start Navigation -->
        <nav class="navbar navbar-default bootsnav navbar-sticky navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">

            <div class="container">

                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="{% url 'interfaces:accueil' %}">GST<span>-FRA</span></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <!-- Afficher le menu uniquement si l'utilisateur est connecté -->
                {% if request.user.is_authenticated %}
                    <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
                        <ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Menu
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'interfaces:accueil' %}">Accueil</a></li>
                                    <li><a class="dropdown-item" href="{% url 'interfaces:absence' %}">Absence</a></li>
                                    <li><a class="dropdown-item" href="{% url 'interfaces:historiques' %}">Historiques</a></li>
                                    <li><a class="dropdown-item" href="{% url 'interfaces:list_personnel' %}">Personnels</a></li>
                                    <!-- Afficher le lien Admin uniquement pour les superutilisateurs -->
                                    {% if request.user.is_superuser %}
                                        <li><a class="dropdown-item" href="admin/">Admin</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                {% endif %}
                <!-- /.navbar-collapse -->
            </div><!--/.container-->
            
        </nav><!--/nav-->
        <!-- End Navigation -->
    </div><!--/.header-area-->
    <div class="clearfix"></div>
</section>

AppGST/templates/bases/header2.html
<section class="top-area">
  <div class="header-area">
      <!-- Start Navigation -->
    <nav class="navbar navbar-default bootsnav navbar-sticky navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          {% include "bases/rechercher_absence.html" %}
        </div>
      </div>
    </nav><!--/nav-->
      <!-- End Navigation -->
  </div><!--/.header-area-->
  <div class="clearfix"></div>
</section>

AppGST/templates/bases/index.html
<!doctype html>
<html class="no-js" lang="en">
	{% load static %}

    <head>
        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        ->
        <!- title of site -->
		<title> GST-{% block title %} {% endblock title %}</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="{% static 'assets/logo/favicon.png' %}">
       
        

    </head>
	
	<body>
		{% block header %}
			{% include "bases/header.html" %}	
		{% endblock header %}

		{% block content %}
		{% endblock content %}
		
		{% block footer %}
			{% include "bases/footer.html" %}
		{% endblock footer %}

		{% block stylesheet %}
			<!--font-awesome.min.css-->
			<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css'%}">

			<!--linear icon css-->
			<link rel="stylesheet" href="{% static 'assets/css/linearicons.css'%}">
	
			<!--animate.css-->
			<link rel="stylesheet" href="{% static 'assets/css/animate.css'%}">
	
			<!--flaticon.css-->
			<link rel="stylesheet" href="{% static 'assets/css/flaticon.css'%}">
			<!--slick.css-->
			<link rel="stylesheet" href="{% static 'assets/css/slick.css'%}">
			<link rel="stylesheet" href="{% static 'assets/css/slick-theme.css'%}">
			<!--bootstrap.min.css-->
			<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}">
			<!-- bootsnav -->
			<link rel="stylesheet" href="{% static 'assets/css/bootsnav.css'%}">	
			<!--style.css-->
			<link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
			<!--responsive.css-->
			<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/fonts.googleapis.css' %}">
		{% endblock stylesheet %}

		{% block javascript %}
			<script src="{% static 'assets/js/jquery.js'%}"></script>
			<!--bootstrap.min.js-->
			<script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
			<!-- bootsnav js -->
			<script src="{% static 'assets/js/bootsnav.js'%}"></script>
			<!--feather.min.js-->
			<script  src="{% static 'assets/js/feather.min.js'%}"></script>
			<!-- counter js -->
			<script src="{% static 'assets/js/jquery.counterup.min.js'%}"></script>
			<script src="{% static 'assets/js/waypoints.min.js'%}"></script>
			<!--slick.min.js-->
			<script src="{% static 'assets/js/slick.min.js'%}"></script>
			<!--Custom JS-->
			<script src="{% static 'assets/js/custom.js' %}"></script>
            <script src="{% static 'assets/js/cdnjs.cloudflare.js' %}"></script>
        
		{% endblock javascript %}
    </body>
	
</html>

AppGST/templates/bases/rechercher.html
<form   action='{% url "interfaces:rechercher" %}' class="navbar-form navbar-right d-flex" role="search">
    <div class="input-group">
        <input type="search" class="form-control" placeholder="Rechercher" name="search">
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span> 
    </div><!-- /input-group -->
</form>

AppGST/templates/bases/rechercher_absence.html
<form   action='{% url "interfaces:rechercher_absence" %}' class="navbar-form navbar-right d-flex" role="search">
    <div class="input-group">
        <input type="search" class="form-control" placeholder="Rechercher" name="search">
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span> 
    </div><!-- /input-group -->
    
</form>