AppGST/AppGST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',include('interfaces.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppGST/interfaces/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import HistogrammeAbsencesView, HistogrammeAbsencesViews



app_name='interfaces'
urlpatterns = [
    path('',views.accueil, name='accueil'),
    path('rechercher/', views.rechercher, name='rechercher'),
    path('rechercher_absence/', views.rechercher_absence, name='rechercher_absence'),

    
    path('ajouter_personnel/', views.ajouter_personnel, name='ajouter_personnel'),
    path('list_personnel/', views.list_personnel, name='list_personnel'),
    path('info_personnel/<int:matricule>/', views.info_personnel, name='info_personnel'),
    path('delete_personnel/<int:matricule>/', views.delete_personnel, name='delete_personnel'),
    path('edit_personnel/<int:matricule>/', views.edit_personnel, name='edit_personnel'),


    path('ajouter_absence/', views.ajouter_absence, name='ajouter_absence'),
    path('une_absence/<int:matricule>/', views.une_absence, name='une_absence'),
    path('historiques/', views.historiques, name='historiques'),
    path('absence/', views.absence, name='absence'),
    path('absences_personnel/<int:matricule>/', views.absences_personnel, name='absences_personnel'),
    path('edit_absence/<int:id>/', views.edit_absence, name='edit_absence'),
    path('delete_absence/<int:id>/', views.delete_absence, name='delete_absence'),
    path('disponibilite/', views.disponibilite, name='disponibilite'),


    path('histogramme-absences/', HistogrammeAbsencesView.as_view(), name='histogramme-absences'),
    path('histogramme-absences_anote/', HistogrammeAbsencesViews.as_view(), name='histogramme-absences_anote'),


]

AppGST/interfaces/models.py
from django.db import models
from datetime import datetime, timedelta

class Absence(models.Model):
    # Choix de type d'absence
    TYPE_ABSENCE_CHOICES = (
        ('ASM', 'ASM'),
        ('PLD', 'PLD'),
        ('PCD', 'PCD'),
        ('Repos_médical', 'Repos médical'),
        ('Service_intérieur', 'Service intérieur'),
    )

    # Choix de motifs pour chaque type d'absence
    MOTIF_PCD_CHOICES = (
        ('Recuperation_de_travail', 'Récupération de travail'),
        ('Recuperation_de_garde', 'Récupération de garde'),
        ('Affaires_administratives', 'Affaires administratives'),
        ('Recuperation_apres_mission', 'Récupération après retour de mission'),
        ('Problemes_sociaux', 'Problèmes sociaux'),
        ('Recuperation_de_permanence', 'Récupération de permanence'),
        ('Preparation_a_la_garde', 'Préparation à la garde'),
    )

    MOTIF_PLD_CHOICES = (
        ('Droit_annuel', 'Droit annuel'),
    )

    MOTIF_SERVICE_INTERIEUR_CHOICES = (
        ('Garde', 'Garde'),
        ('Mission', 'Mission'),
        ('Detache', 'Détaché'),
        ('Cours', 'Cours')
    )

    MOTIF_REPOS_MEDICAL_CHOICES = (
        ('Repos_médical', 'Repos médical'),
        ('PTC','PTC'),
        ('Consultation_médicale', 'Consultation médicale'),
    )

    MOTIF_ASM_CHOICES = (
        ('ASM', 'ASM'),
        ('Retard','Retard')
    )
    STATUT_CHOICES=(
        ('Actuelle','Actuelle'),
        ('Passée','Passée')
    )

    # Champs du modèle
    personnel = models.ForeignKey('MembrePersonnel', on_delete=models.CASCADE)
    type_absence = models.CharField(max_length=250, choices=TYPE_ABSENCE_CHOICES, default='ASM')

    date_depart = models.DateField(null=True)
    heure_depart = models.TimeField(null=True)
    date_arrivee = models.DateField(blank=True, null=True)
    heure_arrivee = models.TimeField(blank=True, null=True)

    # Champ pour stocker la durée d'absence en heures
    duree_absence = models.FloatField(default=0.0)

    # Champs de motifs spécifiques pour chaque type d'absence
    motif_pcd = models.CharField(max_length=50, choices=MOTIF_PCD_CHOICES, null=True, blank=True)
    motif_pld = models.CharField(max_length=50, choices=MOTIF_PLD_CHOICES, null=True, blank=True)
    motif_asm = models.CharField(max_length=50, choices=MOTIF_ASM_CHOICES, null=True, blank=True)
    motif_repos_medical = models.CharField(max_length=50, choices=MOTIF_REPOS_MEDICAL_CHOICES, null=True, blank=True, default='Repos_médical')
    motif_service_interieur = models.CharField(max_length=50, choices=MOTIF_SERVICE_INTERIEUR_CHOICES, null=True, blank=True)
    statut=models.CharField(max_length=30, default='Passée', choices=STATUT_CHOICES, verbose_name="Statut")



    def get_motif_specific(self):
        # Renvoie le motif spécifique en fonction du type d'absence
        if self.type_absence == 'PCD':
            return self.motif_pcd
        elif self.type_absence == 'PLD':
            return self.motif_pld
        elif self.type_absence == 'ASM':
            return self.motif_asm
        elif self.type_absence == 'Repos_médical':
            return self.motif_repos_medical
        elif self.type_absence == 'Service_intérieur':
            return self.motif_service_interieur
        return None  # Retourne None si aucun type d'absence ne correspond

    @property
    def motif_specific(self):
        return self.get_motif_specific()
    
    def save(self, *args, **kwargs):
        # Calcul de la durée d'absence si toutes les données sont présentes
        if self.date_depart and self.heure_depart and self.date_arrivee and self.heure_arrivee:
            depart = datetime.combine(self.date_depart, self.heure_depart)
            arrivee = datetime.combine(self.date_arrivee, self.heure_arrivee)
            if arrivee > depart:
                duree = (arrivee - depart).total_seconds() / 3600  # Convertir en heures
                self.duree_absence = round(duree, 2)
        super().save(*args, **kwargs)

AppGST/interfaces/forms.py
from django import forms
from .models import Absence
from .autre_models import MembrePersonnel
from django.core.exceptions import ValidationError
from datetime import datetime


class FichePersonnelForm(forms.ModelForm):
    nom = forms.CharField(label="Nom :", widget=forms.TextInput(attrs={'class': 'form-control'}))
    prenom = forms.CharField(label="Prénom :", widget=forms.TextInput(attrs={'class': 'form-control'}))
    matricule = forms.IntegerField(label="Matricule :", widget=forms.TextInput(attrs={'class': 'form-control'}))
    grade = forms.ChoiceField(label="Grade :", choices=(('Soldat deuxieme classe','Soldat deuxième classe'),
        ('Soldat première classe','Soldat prémière classe'),
        ('Caporal','Caporal'),
        ('Caporal chef','Caporal chef'),
        ('Sergent', 'Sergent'),
        ('Sergent chef','Sergent Chef'),
        ('Adjudant','Adjudant'),
        ('Adjudant chef','Adjudant chef'),
        ('Aspirant','Aspirant'),
        ('Sous lieutenant','Sous lieutenant'),
        ('Lieutenant','Lieutenant'),
        ('Capitaine','Capitaine'),
        ('Commandant','Commandant'),
        ('Lieutenant colonel','Lieutenant colonel'),
        ('Colonel','Colonel'),
        ('Colonel major','Colonel major'),
        ('Géneral de brigade aerienne','Géneral de brigade aerienne'),
        ('Géneral de division','Géneral de division'),
        ("Géneral de corps d'armée", "Géneral de corps d'armée"),
        ("Géneral d'armée","Géneral d'armée")

    ), widget=forms.Select(attrs={'class': 'form-control',}))
    naissance = forms.DateField(label="Date de naissance :", widget=forms.DateInput(attrs={'class': 'form-control',}))
    sexe = forms.ChoiceField(label="Sexe :", choices=(('M', 'Masculin'), ('F', 'Féminin')), widget=forms.Select(attrs={'class': 'form-control'}))
    service = forms.ChoiceField(label="Service :",choices=(('SGMA1','SGMA1'),('SGMA2','SGMA2'),('SGMA3','SGMA3'),('SGAS','SGAS'),('SGMMR','SGMMR'),('SGRT','SGRT'),('BCT','BCT'),('BST','BST'),('BPI','BPI'),('BTD','BTD'),('Secretariat','Secretariat'),('Comptabilité','Comptabilité'),('Fourier','Fourier')), widget=forms.Select(attrs={'class': 'form-control',}))
    numero = forms.IntegerField(label="Numéro de téléphone :", widget=forms.NumberInput(attrs={'class': 'form-control',}))
    email = forms.EmailField(label="Email :", widget=forms.EmailInput(attrs={'class': 'form-control',}))
    photo = forms.ImageField(label="Image", required=False)

    class Meta:
        model = MembrePersonnel
        fields = ['nom', 'prenom', 'naissance', 'sexe', 'matricule', 'grade', 'service', 'numero', 'email', 'photo']


class AbsenceForm(forms.ModelForm):
    class Meta:
        model = Absence
        fields = [
            'personnel',
            'type_absence',
            'date_depart',
            'heure_depart',
            'date_arrivee',
            'heure_arrivee',
            'motif_pcd',
            'motif_pld',
            'motif_asm',
            'motif_repos_medical',
            'motif_service_interieur',
        ]
        labels = {
            'personnel': 'Membre du personnel',
            'type_absence': 'Type d\'absence',
            'date_depart': 'Date de départ',
            'heure_depart': 'Heure de départ',
            'date_arrivee': 'Date d\'arrivée',
            'heure_arrivee': 'Heure d\'arrivée',
            'motif_pcd': 'Motif PCD',
            'motif_pld': 'Motif PLD',
            'motif_asm': 'Motif ASM',
            'motif_repos_medical': 'Motif repos médical',
            'motif_service_interieur': 'Motif service intérieur',
        }
        widgets = {
            'personnel': forms.Select(attrs={'class': 'form-control'}),
            'type_absence': forms.Select(attrs={'class': 'form-control'}),
            'date_depart': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'heure_depart': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'date_arrivee': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'heure_arrivee': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'motif_pcd': forms.Select(attrs={'class': 'form-control'}),
            'motif_pld': forms.Select(attrs={'class': 'form-control'}),
            'motif_asm': forms.Select(attrs={'class': 'form-control'}),
            'motif_repos_medical': forms.Select(attrs={'class': 'form-control'}),
            'motif_service_interieur': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Masquer les champs de motifs spécifiques par défaut
        self.fields['motif_pcd'].widget.attrs.update({'hidden': True})
        self.fields['motif_pld'].widget.attrs.update({'hidden': True})
        self.fields['motif_asm'].widget.attrs.update({'hidden': True})
        self.fields['motif_repos_medical'].widget.attrs.update({'hidden': True})
        self.fields['motif_service_interieur'].widget.attrs.update({'hidden': True})
    
        # Afficher les champs appropriés en fonction du type d'absence sélectionné
        type_absence = self.data.get('type_absence', self.initial.get('type_absence'))
        if type_absence:
            if type_absence == 'PCD':
                self.fields['motif_pcd'].widget.attrs.pop('hidden')
            elif type_absence == 'PLD':
                self.fields['motif_pld'].widget.attrs.pop('hidden')
            elif type_absence == 'ASM':
                self.fields['motif_asm'].widget.attrs.pop('hidden')
            elif type_absence == 'Repos_médical':
                self.fields['motif_repos_medical'].widget.attrs.pop('hidden')
            elif type_absence == 'Service_intérieur':
                self.fields['motif_service_interieur'].widget.attrs.pop('hidden')

"""class AbsenceForm(forms.ModelForm):
    # Ajout d'un champ pour le type d'absence
    type_absence = forms.ChoiceField(
        label='Type d\'absence',
        choices=Absence.TYPE_ABSENCE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    
    # Ajout de champs pour la nature et le lieu (si besoin)
    nature = forms.CharField(label='Nature', max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lieu = forms.CharField(label='Lieu', max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Absence
        fields = [
            'personnel',
            'type_absence',
            'motif',
            'date_depart',
            'heure_depart',
            'date_arrivee',
            'heure_arrivee',
            'duree_absence',
            'nature',
            'lieu'
        ]
        labels = {
            'personnel': 'Membre du personnel',
            'type_absence': 'Type d\'absence',
            'motif': 'Motif',
            'date_depart': 'Date de départ',
            'heure_depart': 'Heure de départ',
            'date_arrivee': 'Date d\'arrivée',
            'heure_arrivee': 'Heure d\'arrivée',
            'duree_absence': 'Durée d\'absence',
            'nature': 'Nature',
            'lieu': 'Lieu',
        }
        widgets = {
            'personnel': forms.Select(attrs={'class': 'form-control'}),
            'motif': forms.TextInput(attrs={'class': 'form-control'}),
            'date_depart': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'heure_depart': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'date_arrivee': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'required': False}),
            'heure_arrivee': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time', 'required': False}),
            'duree_absence': forms.NumberInput(attrs={'class': 'form-control', 'readonly': True}),  # Lecture seule
            'nature': forms.TextInput(attrs={'class': 'form-control'}),
            'lieu': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        
        # Ajouter ici des validations personnalisées si nécessaire
        date_depart = cleaned_data.get('date_depart')
        heure_depart = cleaned_data.get('heure_depart')
        date_arrivee = cleaned_data.get('date_arrivee')
        heure_arrivee = cleaned_data.get('heure_arrivee')
        
        # Vous pouvez ajouter des validations spécifiques selon vos besoins
        if date_depart and date_arrivee and date_arrivee < date_depart:
            raise forms.ValidationError("La date d'arrivée doit être postérieure à la date de départ.")
        
        if date_depart and date_arrivee and date_arrivee == date_depart and heure_arrivee and heure_depart and heure_arrivee <= heure_depart:
            raise forms.ValidationError("L'heure d'arrivée doit être postérieure à l'heure de départ.")

        # Vous pouvez ajouter d'autres validations ici, selon vos besoins
        
        return cleaned_data
"""

AppGST/interfaces/templates/pages/ajouter_personnel.html
{% extends "bases/index.html" %}
{% block title %}ajouter un personnel{% endblock title %}
{% block content %}
<h1>Ajouter un personnel: </h1>
<div class="container" style="width: 800px; margin-top: 30px;">
  <form method="POST" class="post-form" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_nom" class="form-label">Nom :</label>
        {{ form.nom }}
      </div>
      <div class="mb-3">
        <label for="id_prenom" class="form-label">Prénom :</label>
        {{ form.prenom }}
      </div>
      <div class="mb-3">
        <label for="id_naissance" class="form-label">Date de naissance :</label>
        {{ form.naissance }}
      </div>
      <div class="mb-3">
        <label for="id_sexe" class="form-label">Sexe :</label>
        {{ form.sexe }}
      </div>
      <div class="mb-3">
        <label for="id_matricule" class="form-label">Matricule :</label>
        {{ form.matricule }}
      </div>
      <div class="mb-3">
        <label for="id_grade" class="form-label">Grade :</label>
        {{ form.grade }}
      </div>
      <div class="mb-3">
        <label for="id_service" class="form-label">Service :</label>
        {{ form.service }}
      </div>
      <div class="mb-3">
        <label for="id_numero" class="form-label">Numéro de téléphone :</label>
        {{ form.numero }}
      </div>
      <div class="mb-3">
        <label for="id_email" class="form-label">Email :</label>
        {{ form.email }}
      </div>
      <div class="mb-3">
        <label for="id_photo" class="form-label">Photo :</label>
        {{ form.photo }}
      </div>
      <br>
      <button type="submit"  class="btn btn-primary"> Enregistrer </button>
  </form>
</div>    

{% endblock content %}

AppGST/interfaces/templates/pages/edit_absence.html
{% extends "bases/index.html" %}
{% block title %}Modification d'une absence{% endblock title %}
{% block content %}
<div class="container" style="width: 800px; margin-top: 30px;">
    <h1>Modification de l'absence: </h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_personnel" class="form-label">Membre du personnel :</label>
            {{ form.personnel }}
        </div>

        <div class="mb-3">
            <label for="id_type_absence" class="form-label">Type d'absence :</label>
            {{ form.type_absence }}
        </div>

         <!-- Champs conditionnels -->
         <div class="mb-3" id="motif_pcd" style="display: none;">
            <label for="id_motif_pcd" class="form-label">Motif PCD :</label>
            {{ form.motif_pcd }}
        </div>

        <div class="mb-3" id="motif_pld" style="display: none;">
            <label for="id_motif_pld" class="form-label">Motif PLD :</label>
            {{ form.motif_pld }}
        </div>

        <div class="mb-3" id="motif_asm" style="display: none;">
            <label for="id_motif_asm" class="form-label">Motif ASM :</label>
            {{ form.motif_asm }}
        </div>

        <div class="mb-3" id="motif_repos_medical" style="display: none;">
            <label for="id_motif_repos_medical" class="form-label">Motif repos médical :</label>
            {{ form.motif_repos_medical }}
        </div>

        <div class="mb-3" id="motif_service_interieur" style="display: none;">
            <label for="id_motif_service_interieur" class="form-label">Motif service intérieur :</label>
            {{ form.motif_service_interieur }}
        </div>
        <div class="mb-3">
            <label for="id_date_depart">Date de Départ:</label>
            {{ form.date_depart }}
            <label for="id_heure_depart">Heure de Départ:</label>
            {{ form.heure_depart }}
        </div>

        <div class="mb-3">
            <label for="id_date_arrivee">Date d'Arrivée:</label>
            {{ form.date_arrivee }}
            <label for="id_heure_arrivee">Heure d'Arrivée:</label>
            {{ form.heure_arrivee }}
            {% if message %}
                <p class="text-danger">{{ message }}</p>
            {% endif %}
            {% if message1 %}
                <p class="text-danger">{{ message1 }}</p>
            {% endif %}
        </div>
        <br>
        <button type="submit" class="btn btn-primary"> Enregistrer </button>
    </form>
</div>

<script>
    // Gestion conditionnelle des champs de motif en fonction du type d'absence
    document.addEventListener("DOMContentLoaded", function() {
        const typeAbsenceField = document.getElementById('id_type_absence');
        const motifPcdField = document.getElementById('motif_pcd');
        const motifPldField = document.getElementById('motif_pld');
        const motifAsmField = document.getElementById('motif_asm');
        const motifReposMedicalField = document.getElementById('motif_repos_medical');
        const motifServiceInterieurField = document.getElementById('motif_service_interieur');

        // Fonction pour afficher/masquer les champs de motif en fonction du type d'absence sélectionné
        function updateMotifFields() {
            const selectedTypeAbsence = typeAbsenceField.value;

            // Masquez tous les champs de motifs au début
            motifPcdField.style.display = 'none';
            motifPldField.style.display = 'none';
            motifAsmField.style.display = 'none';
            motifReposMedicalField.style.display = 'none';
            motifServiceInterieurField.style.display = 'none';

            // Affichez les champs de motifs en fonction du type d'absence sélectionné
            if (selectedTypeAbsence === 'PCD') {
                motifPcdField.style.display = 'block';
            } else if (selectedTypeAbsence === 'PLD') {
                motifPldField.style.display = 'block';
            } else if (selectedTypeAbsence === 'ASM') {
                motifAsmField.style.display = 'block';
            } else if (selectedTypeAbsence === 'Repos_medical') {
                motifReposMedicalField.style.display = 'block';
            } else if (selectedTypeAbsence === 'Service_interieur') {
                motifServiceInterieurField.style.display = 'block';
            }
        }

        // Mettez à jour les champs de motif au chargement de la page
        updateMotifFields();

        // Mettez à jour les champs de motif lorsque le type d'absence change
        typeAbsenceField.addEventListener('change', updateMotifFields);
    });

    // Gestion de la validation de la date et de l'heure
    document.querySelector('form').addEventListener('submit', function(event) {
        const dateDepart = document.getElementById('id_date_depart').value;
        const heureDepart = document.getElementById('id_heure_depart').value;
        const dateArrivee = document.getElementById('id_date_arrivee').value;
        const heureArrivee = document.getElementById('id_heure_arrivee').value;

        if (dateDepart && heureDepart && dateArrivee && heureArrivee) {
            const departDateTime = new Date(`${dateDepart}T${heureDepart}`);
            const arriveeDateTime = new Date(`${dateArrivee}T${heureArrivee}`);

            if (departDateTime >= arriveeDateTime) {
                alert("La date et l'heure d'arrivée doivent être postérieures à la date et l'heure de départ.");
                event.preventDefault();
            }
        }
    });
</script>

{% endblock content %}

AppGST/interfaces/templates/pages/rechercher.html
{% extends "bases/index.html" %}
{% block title %}resultats de recherche{% endblock title %}
{% block content %}
{% include "bases/rechercher.html" %}
<div class="container" style="width: 800px; margin-top: 30px;">
    <h1>Resutats de recherche: </h1>
    <button type="button" class="btn btn-info"><a href="{% url 'interfaces:ajouter_personnel'%}">Ajouter du personnel</a></button>

    <table class="table table-dark table-hover" border="1">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col" class='color'>Prénom et Nom</th>
                <th scope="col" class='color'>Grade</th>
                <th scope="col" class='color'>Service</th>
                <th scope="col" class='color'>Matricule</th>
            </tr>
        </thead>
        <tbody>
            {% for personnel in personnels %}
            <tr>
                <td class='color'>{{ forloop.counter }}</td>
                <td class='color'><a href="{% url 'interfaces:info_personnel' personnel.matricule %}">{{ personnel.prenom }} {{ personnel.nom }}</a></td>
                <td class='color'>{{ personnel.grade }}</td>
                <td class='color'>{{ personnel.service }}</td>
                <td class='color'>{{ personnel.matricule }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

AppGST/interfaces/templates/pages/une_absence.html
{% extends "bases/index.html" %}
{% block title %}Nouvelle absence{% endblock title %}
{% block content %}
<h1>Nouvelle absence</h1>
<div class="container" style="width: 800px; margin-top: 30px;">
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_personnel" class="form-label">Membre du personnel :</label>
            {{ form.personnel }}
        </div>

        <div class="mb-3">
            <label for="id_type_absence" class="form-label">Type d'absence :</label>
            {{ form.type_absence }}
        </div>

        <!-- Champs conditionnels -->
        <div class="mb-3" id="field-motif-pcd" class="hidden">
            <label for="id_motif_pcd" class="form-label">Motif PCD :</label>
            {{ form.motif_pcd }}
        </div>

        <div class="mb-3" id="field-motif-pld" class="hidden">
            <label for="id_motif_pld" class="form-label">Motif PLD :</label>
            {{ form.motif_pld }}
        </div>

        <div class="mb-3" id="field-motif-asm" class="hidden">
            <label for="id_motif_asm" class="form-label">Motif ASM :</label>
            {{ form.motif_asm }}
        </div>

        <div class="mb-3" id="field-motif-repos-medical" class="hidden">
            <label for="id_motif_repos_medical" class="form-label">Motif repos médical :</label>
            {{ form.motif_repos_medical }}
        </div>

        <div class="mb-3" id="field-motif-service-interieur" class="hidden">
            <label for="id_motif_service_interieur" class="form-label">Motif service intérieur :</label>
            {{ form.motif_service_interieur }}
        </div>

        <div class="mb-3">
            <label for="id_date_depart" class="form-label">Date de départ :</label>
            {{ form.date_depart }}
            <label for="id_heure_depart" class="form-label">Heure de départ :</label>
            {{ form.heure_depart }}
        </div>

        <div class="mb-3">
            <label for="id_date_arrivee" class="form-label">Date d'arrivée :</label>
            {{ form.date_arrivee }}
            <label for="id_heure_arrivee" class="form-label">Heure d'arrivée :</label>
            {{ form.heure_arrivee }}
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Identifiez les champs de motif et le champ de type d'absence
        const typeAbsenceField = document.getElementById('id_type_absence');
        const motifFields = {
            PCD: document.getElementById('field-motif-pcd'),
            PLD: document.getElementById('field-motif-pld'),
            ASM: document.getElementById('field-motif-asm'),
            Repos_médical: document.getElementById('field-motif-repos-medical'),
            Service_intérieur: document.getElementById('field-motif-service-interieur')
        };
    
        // Fonction pour masquer/afficher les champs de motif en fonction du type d'absence
        function updateMotifFields() {
            const selectedTypeAbsence = typeAbsenceField.value;
    
            // Masquer tous les champs de motifs par défaut
            for (const field in motifFields) {
                motifFields[field].classList.add('hidden');
            }
    
            // Afficher les champs de motifs en fonction du type d'absence sélectionné
            if (motifFields[selectedTypeAbsence]) {
                motifFields[selectedTypeAbsence].classList.remove('hidden');
            }
        }
    
        // Met à jour les champs de motif au chargement de la page
        updateMotifFields();
    
        // Met à jour les champs de motif lorsque le type d'absence change
        typeAbsenceField.addEventListener('change', updateMotifFields);
    });
    

    // Gestion de la validation de la date et de l'heure
    document.querySelector('form').addEventListener('submit', function(event) {
        const dateDepart = document.getElementById('id_date_depart').value;
        const heureDepart = document.getElementById('id_heure_depart').value;
        const dateArrivee = document.getElementById('id_date_arrivee').value;
        const heureArrivee = document.getElementById('id_heure_arrivee').value;

        if (dateDepart && heureDepart && dateArrivee && heureArrivee) {
            const departDateTime = new Date(`${dateDepart}T${heureDepart}`);
            const arriveeDateTime = new Date(`${dateArrivee}T${heureArrivee}`);

            if (departDateTime >= arriveeDateTime) {
                alert("La date et l'heure d'arrivée doivent être postérieures à la date et l'heure de départ.");
                event.preventDefault();
            }
        }
    });
</script>

{% endblock content %}